version: '3'

networks:
    internal-pod:
        internal: true
    external-pod:
        internal: false

volumes:
    mariadb-dolibarr:
        external: true

services:
    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dolibarr
        ports:
            - "3306:3306"
        networks:
            - internal-pod
            - external-pod
        volumes:
            - mariadb-dolibarr:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mariadb
        depends_on:
            - mariadb
        ports:
            - "8080:80"
        networks:
            - internal-pod
            - external-pod

    web:
        build: .
        environment:
            HOST_USER_ID: $HOST_USER_ID
        volumes:
            - ../../module/dolibarr/htdocs:/var/www/html
            - ../../module/dolibarr/documents:/var/documents
        ports:
            - "80:80"
            - "9000:9000"
        depends_on:
            - mariadb
            - mail
        networks:
            - internal-pod
            - external-pod

    mail:
        image: maildev/maildev
        ports:
            - "8081:80"
            - "25:25"
        networks:
            - internal-pod
            - external-pod