version: '3'

networks:
    internal-pod:
        internal: true
    external-pod:
        internal: false

volumes:
    mariadb-dolibarr:
        external: true
    dolibarr_postgres_metabase:
        external: true

services:
    mariadb:
        image: mariadb:latest
        container_name: dolibarr_mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dolibarr
        ports:
            - "3306:3306"
        networks:
            - internal-pod
            - external-pod
        volumes:
            - mariadb-dolibarr:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: dolibarr_phpmyadmin
        environment:
            PMA_HOST: mariadb
        depends_on:
            - mariadb
        ports:
            - "8080:80"
        networks:
            - internal-pod
            - external-pod

    web:
        build: .
        container_name: dolibarr_web
        environment:
            HOST_USER_ID: $HOST_USER_ID
        volumes:
            - ../../../module/dolibarr/htdocs:/var/www/html
            - ../../../module/dolibarr/documents:/var/documents
        ports:
            - "80:80"
            - "6000:9000"
        depends_on:
            - mariadb
            - mail
        networks:
            - internal-pod
            - external-pod

    mail:
        container_name: dolibarr_maildev
        image: maildev/maildev
        ports:
            - "6081:80"
            - "25:25"
        networks:
            - internal-pod
            - external-pod

    postgres_metabase:
        container_name: dolibarr_postgres_metabase
        image: postgres:latest
        volumes:
            - dolibarr_postgres_metabase:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: metabase
            POSTGRES_USER: metabase
            POSTGRES_PASSWORD: metabase
        networks:
            - internal-pod
            - external-pod

    metalab:
        container_name: dolibarr_metalab
        image : metabase/metabase
        environment:
            MB_DB_TYPE: postgres
            MB_DB_DBNAME: metabase
            MB_DB_PORT: 5432
            MB_DB_USER: metabase
            MB_DB_PASS: metabase
            MB_DB_HOST: dolibarr_postgres_metabase
#        volumes:
#            - /data/metabase/metabase-data:/metabase-data
        networks:
            - internal-pod
            - external-pod
        ports:
            - "6082:3000"
        depends_on:
            - postgres_metabase
