version: '3'

networks:
    internal-pod:
        internal: true
    external-pod:
        internal: false

volumes:
    mariadb-dolibarr:
        external: true

services:
    mariadb:
        image: mariadb:latest
        container_name: dolibarr_mariadb
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: dolibarr
        ports:
            - "3306:3306"
        networks:
            - internal-pod
            - external-pod
        volumes:
            - mariadb-dolibarr:/var/lib/mysql
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: dolibarr_phpmyadmin
        environment:
            PMA_HOST: mariadb
        depends_on:
            - mariadb
        ports:
            - "8080:80"
        networks:
            - internal-pod
            - external-pod

    web:
        build: .
        container_name: dolibarr_web
        environment:
            HOST_USER_ID: $HOST_USER_ID
        volumes:
            - ../../../module/dolibarr/htdocs:/var/www/html:rw
            - ../../../module/dolibarr/documents:/var/documents::rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "80:80"
            - "6000:9000"
        depends_on:
            - mariadb
            - mail
        networks:
            - internal-pod
            - external-pod

    mail:
        container_name: dolibarr_maildev
        image: maildev/maildev
        ports:
            - "6081:80"
            - "25:25"
        networks:
            - internal-pod
            - external-pod
