version: '3.8'

networks:
    internal-pod:
        internal: true
    external-pod:
        internal: false

volumes:
    pgsqldb-dolibarr:
        external: true

services:
    dolstdpg-dolibarr-pgsqldb:
        image: postgres:12.1-alpine
        container_name: dolstdpg_dolibarr_pgsqldb
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_DB: dolibarr
        ports:
            - "5433:5433"
        networks:
            - internal-pod
            - external-pod
        volumes:
            - pgsqldb-dolibarr:/var/lib/postgresql/data/pgdata

    dolstdpg-adminer:
        image: adminer:latest
        ports:
            - 7000:8080
        depends_on:
            - pgsql

    dolstdpg-web-nginx:
        image: nginx:1.18-alpine
        container_name: dolstdpg_dolibarr_nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ../../../module/dolibarr/htdocs:/var/www/html:rw
            - ./nginx/log/:/var/log/nginx/
        ports:
            - "80:80"
        networks:
            - internal-pod
            - external-pod
        depends_on:
            - pgsql
            - mail

    dolstdpg-web-php:
        build: .
        container_name: dolstdpg_dolibarr_web
        volumes:
            - ../../../module/dolibarr/htdocs:/var/www/html:rw
            - ../../../module/dolibarr/documents:/var/documents:rw
        ports:
            - "6000:9003"
        networks:
            - internal-pod
            - external-pod
        depends_on:
            - web-nginx

    dolstdpg-mail:
        image: maildev/maildev
        container_name: dolstdpg-_dolibarr_maildev
        ports:
            - "6081:80"
            - "25:25"
        networks:
            - internal-pod
            - external-pod


