version: '3'

networks:
    internal-pod:
        internal: true
    external-pod:
        internal: false

volumes:
    pgsqldb-dolibarr:
        external: true
    mariadb-metabase:
        external: true

services:
    pgsql:
        image: postgres:12.1-alpine
        container_name: dolibarr_pgsqldb
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_DB: dolibarr
        ports:
            - "5433:5433"
        networks:
            - internal-pod
            - external-pod
        volumes:
            - pgsqldb-dolibarr:/var/lib/postgresql/data/pgdata

    adminer:
        image: adminer:latest
        ports:
            - 7000:8080
        depends_on:
            - pgsql

    web-nginx:
        image: nginx:1.18-alpine
        container_name: dolibarr_nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ../../../module/dolibarr/htdocs:/var/www/html:rw
            - ./nginx/log/:/var/log/nginx/
        ports:
            - "80:80"
        networks:
            - internal-pod
            - external-pod
        depends_on:
            - pgsql
            - mail

    web-php:
        build: .
        container_name: dolibarr_web
        volumes:
            - ../../../module/dolibarr/htdocs:/var/www/html:rw
            - ../../../module/dolibarr/documents:/var/documents:rw
        ports:
            - "6000:9003"
        networks:
            - internal-pod
            - external-pod
        depends_on:
            - web-nginx

    mail:
        image: maildev/maildev
        container_name: dolibarr_maildev
        ports:
            - "6081:80"
            - "25:25"
        networks:
            - internal-pod
            - external-pod

    metalab_mariadb:
        image: mariadb:latest
        container_name: metalab_mariadb
        environment:
            MYSQL_ROOT_PASSWORD: metabase
            MYSQL_DATABASE: metabase
        networks:
            - internal-pod
        volumes:
            - mariadb-metabase:/var/lib/mysql

    metalab:
        container_name: dolibarr_metalab
        image: metabase/metabase
        environment:
            MB_DB_TYPE: mysql
            MB_DB_DBNAME: metabase
            MB_DB_PORT: 3306
            MB_DB_USER: root
            MB_DB_PASS: metabase
            MB_DB_HOST: metalab_mariadb
        networks:
            - internal-pod
            - external-pod
        ports:
            - "6082:3000"
        depends_on:
            - metalab_mariadb
