version: '3.8'

networks:
    dolstdpg-internal-pod:
        internal: true
    dolstdpg-external-pod:
        internal: false

volumes:
    pgsqldb-dolibarr:
        external: true

services:
    dolstdpg-dolibarr-pgsqldb:
        image: postgres:12.1-alpine
        container_name: dolstdpg_dolibarr_pgsqldb
        environment:
            POSTGRES_PASSWORD: ${PGSQL_ROOT_PASSWORD}
            POSTGRES_DB: dolibarr
            PGDATA: /var/lib/postgresql/data/dolibarr/
        ports:
            - "5433:5433"
            - "5432:5432"
        networks:
            - dolstdpg-internal-pod
            - dolstdpg-external-pod
        volumes:
            - pgsqldb-dolibarr:/var/lib/postgresql/data/dolibarr
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

    dolstdpg-adminer:
        image: adminer:latest
        container_name: dolstdpg_adminer
        ports:
            - 7000:8080
        depends_on:
            - dolstdpg-dolibarr-pgsqldb
        networks:
            - dolstdpg-internal-pod
            - dolstdpg-external-pod

    dolstdpg-web-nginx:
        image: nginx:1.18-alpine
        container_name: dolstdpg_dolibarr_nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ../../../module/dolibarr/htdocs:/var/www/html:rw
            - ./nginx/log/:/var/log/nginx/
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "80:80"
        networks:
            - dolstdpg-internal-pod
            - dolstdpg-external-pod
        depends_on:
            - dolstdpg-dolibarr-pgsqldb
            - dolstdpg-mail

    dolstdpg-web-php:
        build: .
        container_name: dolstdpg_dolibarr_web
        volumes:
            - ../../../module/dolibarr/htdocs:/var/www/html:rw
            - ../../../module/dolibarr/documents:/var/documents:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "6000:9003"
        networks:
            - dolstdpg-internal-pod
            - dolstdpg-external-pod
        depends_on:
            - dolstdpg-web-nginx

    dolstdpg-mail:
        image: maildev/maildev
        container_name: dolstdpg_dolibarr_maildev
        ports:
            - "6081:1080"
            - "25:1025"
        networks:
            - dolstdpg-internal-pod
            - dolstdpg-external-pod


