version: '3'

networks:
    internal-pod:
        internal: true
    external-pod:
        internal: false

volumes:
    mariadb-dolibarr:
        external: true
    mariadb-metabase:
        external: true

services:
    mariadb:
        image: mariadb:latest
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8;'
        container_name: dolibarr_mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dolibarr
        ports:
            - "3306:3306"
        networks:
            - internal-pod
            - external-pod
        volumes:
            - mariadb-dolibarr:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: dolibarr_phpmyadmin
        environment:
            PMA_HOST: mariadb
        depends_on:
            - mariadb
        ports:
            - "8080:80"
        networks:
            - internal-pod
            - external-pod

    web-nginx:
        image: nginx:1.18-alpine
        container_name: dolibarr_nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ../../../module/dolibarr/htdocs:/var/www/html:ro
            - ./nginx/log/:/var/log/nginx/
        ports:
            - "80:80"
        networks:
            - internal-pod
            - external-pod
        depends_on:
            - mariadb
            - mail

    web-php:
        build: .
        container_name: dolibarr_web
        volumes:
            - ../../../module/dolibarr/htdocs:/var/www/html
            - ../../../module/dolibarr/documents:/var/documents
        ports:
            - "6000:9003"
        networks:
            - internal-pod
            - external-pod
        depends_on:
            - web-nginx

    mail:
        image: maildev/maildev
        container_name: dolibarr_maildev
        ports:
            - "6081:80"
            - "25:25"
        networks:
            - internal-pod
            - external-pod

    metalab_mariadb:
        image: mariadb:latest
        container_name: metalab_mariadb
        environment:
            MYSQL_ROOT_PASSWORD: metabase
            MYSQL_DATABASE: metabase
        networks:
            - internal-pod
        volumes:
            - mariadb-metabase:/var/lib/mysql

    metalab:
        container_name: dolibarr_metalab
        image: metabase/metabase
        environment:
            MB_DB_TYPE: mysql
            MB_DB_DBNAME: metabase
            MB_DB_PORT: 3306
            MB_DB_USER: root
            MB_DB_PASS: metabase
            MB_DB_HOST: metalab_mariadb
        networks:
            - internal-pod
            - external-pod
        ports:
            - "6082:3000"
        depends_on:
            - metalab_mariadb
